# Derives lv_conf.h from LVGL's lv_conf_template.h: enables the file and
# overrides the handful of options livi-ui depends on. Anything not listed
# keeps the template default, so an LVGL bump picks up new options for free.
function(livi_generate_lv_conf template out)
  file(READ ${template} conf)
  string(REPLACE "#if 0 /*Set it to \"1\" to enable content*/" "#if 1 /* livi-ui */" conf "${conf}")
  string(REPLACE "#if 0 /* Set this to \"1\" to enable content */" "#if 1 /* livi-ui */" conf "${conf}")

  macro(lv_set name value)
    # `#define NAME <anything>` on its own line, keep the trailing comment away
    string(REGEX REPLACE "\n([ \t]*)#define ${name}[ \t]+[^\n]*" "\n\\1#define ${name} ${value}" conf "${conf}")
  endmacro()

  lv_set(LV_COLOR_DEPTH 32)
  lv_set(LV_USE_STDLIB_MALLOC LV_STDLIB_CLIB)
  lv_set(LV_USE_STDLIB_STRING LV_STDLIB_CLIB)
  lv_set(LV_USE_STDLIB_SPRINTF LV_STDLIB_CLIB)
  lv_set(LV_USE_OS LV_OS_NONE)
  lv_set(LV_DEF_REFR_PERIOD 16)
  lv_set(LV_DPI_DEF 96)
  lv_set(LV_USE_LOG 1)
  lv_set(LV_LOG_LEVEL LV_LOG_LEVEL_WARN)
  lv_set(LV_LOG_PRINTF 1)
  lv_set(LV_USE_ASSERT_NULL 1)
  lv_set(LV_USE_ASSERT_MALLOC 1)
  lv_set(LV_FONT_MONTSERRAT_14 1)
  lv_set(LV_FONT_MONTSERRAT_16 1)
  lv_set(LV_FONT_MONTSERRAT_20 1)
  lv_set(LV_FONT_MONTSERRAT_24 1)
  lv_set(LV_FONT_MONTSERRAT_32 1)
  lv_set(LV_FONT_DEFAULT &lv_font_montserrat_16)
  lv_set(LV_USE_FREETYPE 1)
  lv_set(LV_FREETYPE_USE_LVGL_PORT 0)
  lv_set(LV_FREETYPE_CACHE_FT_GLYPH_CNT 512)
  lv_set(LV_USE_WAYLAND 1)
  lv_set(LV_WAYLAND_DIRECT_EXIT 0)
  lv_set(LV_WAYLAND_WINDOW_DECORATIONS 0)
  lv_set(LV_WAYLAND_WL_SHELL 0)
  lv_set(LV_WAYLAND_XDG_SHELL 1)
  lv_set(LV_WAYLAND_USE_DMABUF 0)
  lv_set(LV_USE_DEMO_WIDGETS 0)
  lv_set(LV_USE_DEMO_BENCHMARK 0)
  lv_set(LV_USE_DEMO_MUSIC 0)
  lv_set(LV_USE_SYSMON 0)
  lv_set(LV_USE_PERF_MONITOR 0)
  lv_set(LV_USE_MEM_MONITOR 0)
  lv_set(LV_USE_FS_POSIX 1)
  lv_set(LV_FS_POSIX_LETTER 'A')
  lv_set(LV_FS_POSIX_PATH "\"\"")
  lv_set(LV_FS_POSIX_CACHE_SIZE 0)
  lv_set(LV_USE_LODEPNG 1)
  lv_set(LV_USE_TJPGD 1)
  lv_set(LV_BIN_DECODER_RAM_LOAD 1)
  lv_set(LV_USE_THORVG_INTERNAL 0)
  lv_set(LV_USE_VECTOR_GRAPHIC 0)
  lv_set(LV_USE_SNAPSHOT 1)

  file(WRITE ${out} "${conf}")
endfunction()
